name: Auto generate changelog

on:
  workflow_call:
    inputs:
      git_user:
        required: true
        type: string
      git_name:
        required: true
        type: string
      git_email:
        required: true
        type: string

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Auto generate changelog
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        uses: charmixer/auto-changelog-action@v1.2
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          output: changelog.md
          date_format: '%d/%m/%Y'

      - name: Commit and push
        env:
          PUSH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          GIT_USER: ${{ inputs.git_user }}
          GIT_NAME: ${{ inputs.git_name }}
          GIT_EMAIL: ${{ inputs.git_email }}
        run: |
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"
          git add changelog.md
          git diff --staged --quiet && echo "No changes to changelog.md" && exit 0
          git commit -m 'ci: update changelog.md'
          git push "https://${GIT_USER}:${PUSH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:master
